# Generated by Django 4.2.5 on 2023-10-03 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_addproduct_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Descripción',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
